module.exports = [
  {id: 1, name: "Journey Starter", unlocked: false, description: "Well done on starting your journey!", image_url: "https://previews.dropbox.com/p/thumb/AAv_zbkZmypB8lrfv2SrbCqEawHeRZScVFPkMFUL9wqrHeCUO9tahnT8Ks0x3wVhCvJ4r0oL24_jPm9aYvhZgGsEV1V2m40QSVEflaERZnuHgs5RPqV_M9ssYZvjBhu7l0HDDbCBb8KavYGtwmLFfhtbKeq9J2N8fcZMbo70bANAK-mYAA077dHe4XwkwPMnnwYjYrK_eOAC2qO9qi1V1kgJch9-ApcXKq59lGg6nimRIjarjbZqO4OuVoHdPixhSNcJY62iWdyNmDuXw3aUx8BOhwskiPLgWC4hDUdJWN25i6HLObs4xbm7C8hzzJbRUhdc5WtIXhY9CJfKCfonivGG/p.png?fv_content=true&size_mode=5"}, //wilson
  {id: 2, name: "Consistency", unlocked: false, description: "You achieved 5 meditating sessions in a row!", image_url: "https://previews.dropbox.com/p/thumb/AAsn8TjkXl4V82slHpm0PvRDzj5MuySJx-a9VijJEaLGodw4L78lJF8F1mblMcRT8tzETUoMSxNm-KNyRg0elXise4Cx8ejqg8EDz8_RV81LhiyfeLPxpW4f989E1Mt-K0KM_Bwz7sWdFQySCPxdhpKghCXoPvvZBt8odibc9uzSv84dHoZVXaPs9aoBzR0GyN0PzUfYC8Pktnl8Z1ok41RWs-a6-_vw_XuKvvpjWRjqkaEGXjVTdRdWrqwfs7PzxAD6_08UXduHJMG6JOSaRhGshYpb-V2cUYYXBQBgVQAP6ebQqXtZ0bhySbSKPz_SabXy839deGeefgtmHnycqhaX/p.png?fv_content=true&size_mode=5"},
  {id: 3, name: "Intermediate Meditator", unlocked:  false, description: "Well done on completing the beginner meditation course.", image_url: "https://previews.dropbox.com/p/thumb/AAs4Pq94QOSXNNWbVJ7fB6F1qjrsJT4V-XtyQahs51ptpvcEcqUYfoxDxWKgNJA_CoCzS5kRTqg8fXVGxZuIuQj7RM9LllLzKrmtdYb_QSMhwmpMswSw1_MbZwMN711lbsIpJAzYviOBfvGi65qAATh_TrcQZqtfqvh4UqYpY8QJ3d4kT6V3eCBSH1sAUGR1Esog-tZcl35lbsxHHaimWvaYo_Fxy96KFqacGhAbpNyjyJamVC9aNVpy-glEs1i-W3sYI2aXWUvVZNT4pxxV785IdNIW6795i7vHVdYPvwZ5N8B9sBFwbOy2YxKVx8EmGMLSWzH60pdMaXeg2GFHVig9/p.png?fv_content=true&size_mode=5"}, //yonex
  {id: 4, name: "Advanced Meditator", unlocked: false, description: "Well done on completing the intermediate meditation course.", image_url: "https://previews.dropbox.com/p/thumb/AAu1dmGMKPumT5j8LalFJC5dKoPq3OUPOA9tk79o72mnYK6xZMOlV5SGT3W4z7fvcW7HPhKXgJKK6bTDOouW4zhRsmctgeSGzdSThJulZQWVR2bdp9uAt52x_vfMaxwZJI02CSzlgLOiCID9Upw9uayTIywcnl7aG_p_CbPalg2wdNi53VypKL5ak5zqMPmOnm1RZgdObhUSUMKkNGy1CSWyxRT6scVB07MLHfj8M7_EY7N2Dj11d-Q-yMenxYjCdUCsjDrgeYQbqc9LLjcAnc0bJ7nhqSktvOJGqgnz4i7degMnRIFfwoBzzMKyx2TATHDT0xTZrdaDYtQFADgSs47-/p.png?fv_content=true&size_mode=5"}, //babolat
  {id: 5, name: "Master Meditator", unlocked: false, description: "Well done on completing the expert meditation course.", image_url: "https://previews.dropbox.com/p/thumb/AAvV4lJr6ISA2rP0pO64ypiB3PUUK1jVwBaD4EoabYXmqJA2zzrW7V8KyCl-Vd684hFPXNmxf9R9L8GE4iEwgxFmCJCaFCqqiUVaMnWHqdNqzLhK1KhEij3Jxmz0651sxjYug7UTWcYEK-vL3t_vB2UjttD1mm9cFqxk3VOzEPpFZD8YhtyZ8nGyWGef5c95E2AUTcswXrKMcrvq4WYDxxUbNU0ec57MkK1vB00GGX1l_RMf-sbyFPgyTgHh-5e_S34ppSkWvtLhmGFHY4lrrBo9Fi3wRwsdIp98DXJucQJnTJfk0sfuddMruVRrxlURjHnC7r8tGZAsMLHwwC-CVBaG/p.png?fv_content=true&size_mode=5"},//dunlop
  {id: 6, name: "Super consistent", unlocked: false, description: "You achieved 10 days meditating in a row!", image_url: "https://previews.dropbox.com/p/thumb/AAvXRPM4_KtO6AoFQV71Yon6NjfHoVwEXzftPHjo0ZDYOa1Ks_MVD9ea478ycto9D2txVXGGm1k_tSUwivfFt7Grl8IAAX5qBMJA_0W3l-JOy9KP6PHsj08fqsNVPlx34KP1L0HoF0iFy922FXApCHevovg5V8-AZCHbQZF4EwhFA4zAXipomjUDjGsa1aqdCIRGOevdqWPueDR1ToiW9JmovyPq8yKtTGx9R1YyOrkQQzRNsHnaHHjKTwdJ_LbYBPVzitTWZd_iWnE-a6sAlCe2qU9q75dJiXcO07zZqtj9kGrac_NzvwYOMmo-3H7YV_-6bTArd0KDgCpCwXDS20Zy/p.png?fv_content=true&size_mode=5"},//gamma
  {id: 7, name: "Ultra consistent", unlocked: false, description: "You achieved 15 days meditating in a row!", image_url: "https://previews.dropbox.com/p/thumb/AAs-lU0ip5WA4iqYWCKjeZ6q-BuCjj6iUBmRGrOCReIZL6fJxuzb3WhTJVWKI3S2euV-xSe6fHCvDjKyTP4at9sODQDcKa0_IO_vDRQi-TfLiMliSXT4SW7NyHnu9Z8R_j-gJ305Bp4fzAw5NEcmNrm0oCBacH7lFNYXILO1w5h9DxnYo5JvSMpLOoN2vs34K_rganmVTOCWGMMqisa5wtt3WhH4ZM92V3HI3bEbQZg99D7bkEkcUR4eZZWp_cYtOYrs_U0K1HU-M5ZIBEqG-Zzv2LghQFVjyxM9QquNTciSMlgOPKftZRyUbFTeXFt5FSC_pL7oe879F8GdR4Y-l8HV/p.png?fv_content=true&size_mode=5"},//prince
  {id: 8, name: "Peacefulness", unlocked: false, description: "You completed over half an hour of total time meditating", image_url: "https://previews.dropbox.com/p/thumb/AAvPG7R_IzwPOhqzrVbBYi4f6IKsgFl4yrklg4fAYWciFbgOQzNyqRkY2CAVYAqGu3nrSbIfUflJOA_TwwVuS_6DoLCMleDCy7QiXo4gv2GovgyQo_rhmv1uqzzuDKMdYYG7aIIiNafblQWlfp5aRmDXI2cGFyW9dUwW4TsgVpsZlVjW_pU_PUblabk9UQiXtWr1Xark2QWey-F9yIjo7nk1hIYe86KOJDVId05Rxqqeva68u5RFbn5HUnnSiCi9Oqtkdd_RB5E0FCJyqoMuCoP-oyOsadPb1NqmkPUdkXJ1tfCFtmM7ERCITc0cIOrNy_2_TDtbI4z5DxTU4diZHLql/p.png?fv_content=true&size_mode=5"}, //prokennex
  {id: 9, name: "True Peace", unlocked: false, description: "You completed over an hour of total time meditating", image_url: "https://previews.dropbox.com/p/thumb/AAsJ_cInzqvzUsvlj2O7MMa5AVmKuAWsU2kBkqYWTucZjhlWZikNTWgdjNI5_WGK0j7BWxiZH0A7WJBOIcIKgy-Inpxb2hJReBfYVF6jIegszlCF2hn9Bu6F-Rutaewug5-uFoLrkqXtFg_1G9DAM0UYL8LPLzeWBK8KiMpZTC4IKEgFggKu1ITttQzGp423BjK7M0jl0Gczxq0puBqjaHjksfzdLwvp_1R1Ty-G72kSOE7hXD-YJyAgxCyrh8wBcpVOf7ZsdspScIS--31ZNJLSnE_3ilMTBtocmsTP5IBK0kNG32zCaZZMNY3_UqCH34DFEQZHW5WMUccT7BipkELL/p.png?fv_content=true&size_mode=5"}, //technifibre
  {id: 10, name: "Zen master", unlocked: false, description: "You completed over 100 hours of total time meditating", image_url: "https://previews.dropbox.com/p/thumb/AAtFnWHqSGCTz-2E_YSLPw0ac77k8J8fzDKxtYSox32aBgyxtLm9dVx-zrb_mlksRKBWxfWQ_G6PsSqGA-2GOQGydiMuMk7DHg6UFlXs6zcDtMK22-HhCC1TSlI_oetyoTK_24LYzVg3KzTOewqUR_pnNmRrxZbMFJuEEwtEjM00IVZvAVOOKYik3t8hh2-J5pukgGDRprgGZjmevwvlS6IuSYUBxH9mULsvDMZprs74wILY8cEDIdW1rQMzqEvr_JiWZJiBODLVPJsl3ZclqtZFgrC6y628qinWaL3kEeIFBPfDdG23oBDUPyF2LqlyDhQ79KciWqGUZn6Pp4eY30iU/p.png?fv_content=true&size_mode=5"} //volkl
]