export default {
  LOGIN_START: "LOGIN_START",
  LOGIN_OKAY: "LOGIN_OKAY",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_START: "REGISTER_START",
  REGISTER_OKAY: "REGISTER_OKAY",
  REGISTER_FAIL: "REGISTER_FAIL"
};
